#ifndef DB_CAN_REG_MAP_H
#define DB_CAN_REG_MAP_H

/*
 * THIS FILE IS AUTOGENERATED CODE
 * DO NOT EDIT
*/

#include <stdint.h>
#include <stdbool.h>

#define DBCAN_REG_MAP_HASH 0xAF4C3648
#define REG_COUNT 70
#define REG_STORE_BYTES 456
static uint8_t reg_store[REG_STORE_BYTES] = { [0] = 0x75, [1] = 0x6E, [2] = 0x70, [3] = 0x72, [4] = 0x6F, [5] = 0x76, [6] = 0x69, [7] = 0x73, [8] = 0x69, [9] = 0x6F, [10] = 0x6E, [11] = 0x65, [12] = 0x64, [32] = 0x75, [33] = 0x6E, [34] = 0x70, [35] = 0x72, [36] = 0x6F, [37] = 0x76, [38] = 0x69, [39] = 0x73, [40] = 0x69, [41] = 0x6F, [42] = 0x6E, [43] = 0x65, [44] = 0x64, [429] = 0x01, [430] = 0x01, [431] = 0x0A, [432] = 0x01, [435] = 0x01, [436] = 0x01, [438] = 0x04, [442] = 0x01, [452] = 0x01, [454] = 0x0A, [455] = 0x01 };


typedef enum {
    REG_R   = 1u << 0,
    REG_W   = 1u << 1,
    REG_CMD = 1u << 2
} reg_perm_t;

typedef enum {
    DTYPE_NONE = 0,
	DTYPE_BOOL = 1,
	DTYPE_UINT = 2,
	DTYPE_INT = 3,
	DTYPE_FLOAT = 4,
	DTYPE_STRING = 5,
	DTYPE_ENUM = 6,
	DTYPE_STRUCT = 7,
} dtype_t;

typedef enum {
    FIELD_DTYPE_NONE = 0,
	FIELD_DTYPE_BOOL = 1,
	FIELD_DTYPE_UINT = 2,
	FIELD_DTYPE_INT = 3,
	FIELD_DTYPE_FLOAT = 4,
	FIELD_DTYPE_ENUM = 5,
} field_dtype_t;

typedef enum {
	REG_HARDWARE = 0,
	REG_HARDWARE_BOARD_TYPE = 1,
	REG_HARDWARE_BOARD_NAME = 2,
	REG_HARDWARE_MAJOR_VERSION = 3,
	REG_HARDWARE_MINOR_VERSION = 4,
	REG_HARDWARE_PATCH_VERSION = 5,
	REG_HARDWARE_MCU_UID = 6,
	REG_FIRMWARE = 7,
	REG_FIRMWARE_BOOT = 8,
	REG_FIRMWARE_BOOT_MAJOR_VERSION = 9,
	REG_FIRMWARE_BOOT_MINOR_VERSION = 10,
	REG_FIRMWARE_BOOT_PATCH_VERSION = 11,
	REG_FIRMWARE_PROTOCOL = 12,
	REG_FIRMWARE_PROTOCOL_MAJOR_VERSION = 13,
	REG_FIRMWARE_PROTOCOL_MINOR_VERSION = 14,
	REG_FIRMWARE_PROTOCOL_PATCH_VERSION = 15,
	REG_FIRMWARE_APP = 16,
	REG_FIRMWARE_APP_MAJOR_VERSION = 17,
	REG_FIRMWARE_APP_MINOR_VERSION = 18,
	REG_FIRMWARE_APP_PATCH_VERSION = 19,
	REG_FAULTS = 20,
	REG_FAULTS_CTRL = 21,
	REG_FAULTS_CTRL_CLEAR_FAULTS = 22,
	REG_FAULTS_CTRL_CLEAR_LOG = 23,
	REG_FAULTS_DATA = 24,
	REG_FAULTS_DATA_HEALTH = 25,
	REG_FAULTS_DATA_ACTIVE_CODES = 26,
	REG_FAULTS_DATA_FAULT_LOG = 27,
	REG_FAULTS_BEHAVIOR = 28,
	REG_FAULTS_BEHAVIOR_REPORT_ON_EVENT = 29,
	REG_FAULTS_BEHAVIOR_REPORT_ON_INTERVAL = 30,
	REG_FAULTS_BEHAVIOR_INTERVAL = 31,
	REG_FAULTS_BEHAVIOR_RESPONSE = 32,
	REG_ID = 33,
	REG_ID_VALUE = 34,
	REG_ID_VALUE_UID = 35,
	REG_ID_VALUE_LOWEST_AVAILABLE_ID = 36,
	REG_ID_VALUE_PERSISTS = 37,
	REG_ID_VALUE_AUTO_ID_MEATHOD = 38,
	REG_ID_AUTO_ID = 39,
	REG_ID_AUTO_ID_SELECT_NEXT = 40,
	REG_ID_AUTO_ID_SELECT_PREVIOUS = 41,
	REG_NODE_STATE = 42,
	REG_NODE_STATE_CHANGE = 43,
	REG_NODE_STATE_CHANGE_REBOOT = 44,
	REG_NODE_STATE_CHANGE_ENTER_BOOT = 45,
	REG_NODE_STATE_CHANGE_START = 46,
	REG_NODE_STATE_CHANGE_STOP = 47,
	REG_NODE_STATE_CHANGE_SLEEP = 48,
	REG_NODE_STATE_CHANGE_DEEP_SLEEP = 49,
	REG_NODE_STATE_CHANGE_WAKEUP = 50,
	REG_NODE_STATE_CHANGE_NO_ID = 51,
	REG_NODE_STATE_CURRENT = 52,
	REG_NODE_STATE_CURRENT_STATE = 53,
	REG_NODE_STATE_CURRENT_REASON_IN_BOOT = 54,
	REG_NODE_STATE_CURRENT_REASON_STOPPED = 55,
	REG_NODE_STATE_CURRENT_REASON_SLEEPING = 56,
	REG_NODE_STATE_CURRENT_REASON_DEEP_SLEEPING = 57,
	REG_NODE_STATE_BEHAVIOR = 58,
	REG_NODE_STATE_BEHAVIOR_AUTO_JUMP = 59,
	REG_NODE_STATE_BEHAVIOR_WAKE_ON_TIMER = 60,
	REG_NODE_STATE_BEHAVIOR_SLEEP_WHEN_INACTIVE = 61,
	REG_NODE_STATE_BEHAVIOR_DEEP_SLEEP_WHEN_INACTIVE = 62,
	REG_NODE_STATE_BEHAVIOR_WAKE_TIMER_PERIOD = 63,
	REG_NODE_STATE_BEHAVIOR_INACTIVE_TIME = 64,
	REG_NODE_STATE_HEARTBEAT = 65,
	REG_NODE_STATE_HEARTBEAT_MY_BROADCAST = 66,
	REG_NODE_STATE_HEARTBEAT_REQUIRE_RECIEVE = 67,
	REG_NODE_STATE_HEARTBEAT_TIME_TO_ACT = 68,
	REG_NODE_STATE_HEARTBEAT_DEHAVIOR_ON_LOOSE = 69,
} reg_map_t;

typedef struct {
    uint16_t    width_bytes;
    dtype_t     dtype;
    reg_perm_t  perms;
    uint16_t    offset;
    bool        persist;
    int32_t     min;
    int32_t     max;
} reg_desc_t;

typedef enum {
	HEALTH_OK = 0,
	HEALTH_PASSIVE_FAULT = 1,
	HEALTH_BLOCKING_FAULT = 2,
	HEALTH_DAMAGED_HARDWARE = 3,
} faults_data_health_t;

typedef enum {
	ACTIVE_CODES_NO_FAULT = 0,
} faults_data_active_codes_t;

typedef enum {
	RESPONSE_REPORT_ONLY = 0,
	RESPONSE_STOP_OUTPUTS = 1,
	RESPONSE_SAFE_HOLD = 2,
} faults_behavior_response_t;

typedef enum {
	AUTO_ID_MEATHOD_DISABLED = 0,
	AUTO_ID_MEATHOD_GPIO_SELECT = 1,
	AUTO_ID_MEATHOD_DYNAMIC = 2,
} id_value_auto_id_meathod_t;

typedef enum {
	STATE_INITALIZING = 0,
	STATE_IN_BOOT = 1,
	STATE_RUNNING = 2,
	STATE_STOPPED = 3,
	STATE_SLEEPING = 4,
	STATE_DEEP_SLEEP = 5,
	STATE_NO_ID = 6,
} node_state_current_state_t;

typedef enum {
	REASON_IN_BOOT_NOT_IN_BOOT = 0,
	REASON_IN_BOOT_REQUESTED = 1,
	REASON_IN_BOOT_FAILED_TO_JUMP = 2,
	REASON_IN_BOOT_WAITING_FOR_JUMP_CMD = 3,
	REASON_IN_BOOT_NO_APP = 4,
} node_state_current_reason_in_boot_t;

typedef enum {
	REASON_STOPPED_NOT_STOPPED = 0,
	REASON_STOPPED_REQUESTED = 1,
	REASON_STOPPED_FAULT = 2,
} node_state_current_reason_stopped_t;

typedef enum {
	REASON_SLEEPING_NOT_SLEEPING = 0,
	REASON_SLEEPING_REQUESTED = 1,
	REASON_SLEEPING_TIMER_TRIGGER = 2,
	REASON_SLEEPING_INACTIVITY = 3,
} node_state_current_reason_sleeping_t;

typedef enum {
	REASON_DEEP_SLEEPING_NOT_SLEEPING = 0,
	REASON_DEEP_SLEEPING_REQUESTED = 1,
	REASON_DEEP_SLEEPING_TIMER_TRIGGER = 2,
	REASON_DEEP_SLEEPING_INACTIVITY = 3,
} node_state_current_reason_deep_sleeping_t;

typedef enum {
	DEHAVIOR_ON_LOOSE_WARNING = 0,
	DEHAVIOR_ON_LOOSE_FAULT = 1,
	DEHAVIOR_ON_LOOSE_STOP = 2,
	DEHAVIOR_ON_LOOSE_EMERGENCY = 3,
} node_state_heartbeat_dehavior_on_loose_t;


typedef struct {
	uint32_t timestamp;
	uint16_t code;
} faults_data_fault_log_t;


static const reg_desc_t reg_table[] = {
	[REG_HARDWARE] = { .width_bytes = 100, .dtype = DTYPE_NONE, .perms = REG_R, .offset = 0, .persist = false, .min = 1, .max = 0 },
	[REG_HARDWARE_BOARD_TYPE] = { .width_bytes = 32, .dtype = DTYPE_STRING, .perms = REG_R, .offset = 0, .persist = false, .min = 1, .max = 0 },
	[REG_HARDWARE_BOARD_NAME] = { .width_bytes = 32, .dtype = DTYPE_STRING, .perms = REG_R, .offset = 32, .persist = false, .min = 1, .max = 0 },
	[REG_HARDWARE_MAJOR_VERSION] = { .width_bytes = 8, .dtype = DTYPE_UINT, .perms = REG_R, .offset = 64, .persist = false, .min = 1, .max = 0 },
	[REG_HARDWARE_MINOR_VERSION] = { .width_bytes = 8, .dtype = DTYPE_UINT, .perms = REG_R, .offset = 72, .persist = false, .min = 1, .max = 0 },
	[REG_HARDWARE_PATCH_VERSION] = { .width_bytes = 8, .dtype = DTYPE_UINT, .perms = REG_R, .offset = 80, .persist = false, .min = 1, .max = 0 },
	[REG_HARDWARE_MCU_UID] = { .width_bytes = 12, .dtype = DTYPE_UINT, .perms = REG_R, .offset = 88, .persist = false, .min = 1, .max = 0 },
	[REG_FIRMWARE] = { .width_bytes = 72, .dtype = DTYPE_NONE, .perms = 0, .offset = 100, .persist = false, .min = 1, .max = 0 },
	[REG_FIRMWARE_BOOT] = { .width_bytes = 24, .dtype = DTYPE_NONE, .perms = REG_R, .offset = 100, .persist = false, .min = 1, .max = 0 },
	[REG_FIRMWARE_BOOT_MAJOR_VERSION] = { .width_bytes = 8, .dtype = DTYPE_UINT, .perms = REG_R, .offset = 100, .persist = false, .min = 1, .max = 0 },
	[REG_FIRMWARE_BOOT_MINOR_VERSION] = { .width_bytes = 8, .dtype = DTYPE_UINT, .perms = REG_R, .offset = 108, .persist = false, .min = 1, .max = 0 },
	[REG_FIRMWARE_BOOT_PATCH_VERSION] = { .width_bytes = 8, .dtype = DTYPE_UINT, .perms = REG_R, .offset = 116, .persist = false, .min = 1, .max = 0 },
	[REG_FIRMWARE_PROTOCOL] = { .width_bytes = 24, .dtype = DTYPE_NONE, .perms = REG_R, .offset = 124, .persist = false, .min = 1, .max = 0 },
	[REG_FIRMWARE_PROTOCOL_MAJOR_VERSION] = { .width_bytes = 8, .dtype = DTYPE_UINT, .perms = REG_R, .offset = 124, .persist = false, .min = 1, .max = 0 },
	[REG_FIRMWARE_PROTOCOL_MINOR_VERSION] = { .width_bytes = 8, .dtype = DTYPE_UINT, .perms = REG_R, .offset = 132, .persist = false, .min = 1, .max = 0 },
	[REG_FIRMWARE_PROTOCOL_PATCH_VERSION] = { .width_bytes = 8, .dtype = DTYPE_UINT, .perms = REG_R, .offset = 140, .persist = false, .min = 1, .max = 0 },
	[REG_FIRMWARE_APP] = { .width_bytes = 24, .dtype = DTYPE_NONE, .perms = REG_R, .offset = 148, .persist = false, .min = 1, .max = 0 },
	[REG_FIRMWARE_APP_MAJOR_VERSION] = { .width_bytes = 8, .dtype = DTYPE_UINT, .perms = REG_R, .offset = 148, .persist = false, .min = 1, .max = 0 },
	[REG_FIRMWARE_APP_MINOR_VERSION] = { .width_bytes = 8, .dtype = DTYPE_UINT, .perms = REG_R, .offset = 156, .persist = false, .min = 1, .max = 0 },
	[REG_FIRMWARE_APP_PATCH_VERSION] = { .width_bytes = 8, .dtype = DTYPE_UINT, .perms = REG_R, .offset = 164, .persist = false, .min = 1, .max = 0 },
	[REG_FAULTS] = { .width_bytes = 261, .dtype = DTYPE_NONE, .perms = 0, .offset = 172, .persist = false, .min = 1, .max = 0 },
	[REG_FAULTS_CTRL] = { .width_bytes = 0, .dtype = DTYPE_NONE, .perms = REG_CMD, .offset = 172, .persist = false, .min = 1, .max = 0 },
	[REG_FAULTS_CTRL_CLEAR_FAULTS] = { .width_bytes = 0, .dtype = DTYPE_NONE, .perms = REG_CMD, .offset = 172, .persist = false, .min = 1, .max = 0 },
	[REG_FAULTS_CTRL_CLEAR_LOG] = { .width_bytes = 0, .dtype = DTYPE_NONE, .perms = REG_CMD, .offset = 172, .persist = false, .min = 1, .max = 0 },
	[REG_FAULTS_DATA] = { .width_bytes = 257, .dtype = DTYPE_NONE, .perms = REG_R, .offset = 172, .persist = false, .min = 1, .max = 0 },
	[REG_FAULTS_DATA_HEALTH] = { .width_bytes = 1, .dtype = DTYPE_ENUM, .perms = REG_R, .offset = 172, .persist = false, .min = 1, .max = 0 },
	[REG_FAULTS_DATA_ACTIVE_CODES] = { .width_bytes = 64, .dtype = DTYPE_ENUM, .perms = REG_R, .offset = 173, .persist = false, .min = 1, .max = 0 },
	[REG_FAULTS_DATA_FAULT_LOG] = { .width_bytes = 192, .dtype = DTYPE_STRUCT, .perms = REG_R, .offset = 237, .persist = false, .min = 1, .max = 0 },
	[REG_FAULTS_BEHAVIOR] = { .width_bytes = 4, .dtype = DTYPE_NONE, .perms = REG_R | REG_W, .offset = 429, .persist = false, .min = 1, .max = 0 },
	[REG_FAULTS_BEHAVIOR_REPORT_ON_EVENT] = { .width_bytes = 1, .dtype = DTYPE_BOOL, .perms = REG_R | REG_W, .offset = 429, .persist = true, .min = 1, .max = 0 },
	[REG_FAULTS_BEHAVIOR_REPORT_ON_INTERVAL] = { .width_bytes = 1, .dtype = DTYPE_BOOL, .perms = REG_R | REG_W, .offset = 430, .persist = true, .min = 1, .max = 0 },
	[REG_FAULTS_BEHAVIOR_INTERVAL] = { .width_bytes = 1, .dtype = DTYPE_UINT, .perms = REG_R | REG_W, .offset = 431, .persist = true, .min = 1, .max = 0 },
	[REG_FAULTS_BEHAVIOR_RESPONSE] = { .width_bytes = 1, .dtype = DTYPE_ENUM, .perms = REG_R | REG_W, .offset = 432, .persist = true, .min = 1, .max = 0 },
	[REG_ID] = { .width_bytes = 4, .dtype = DTYPE_NONE, .perms = 0, .offset = 433, .persist = false, .min = 1, .max = 0 },
	[REG_ID_VALUE] = { .width_bytes = 4, .dtype = DTYPE_NONE, .perms = REG_R | REG_W, .offset = 433, .persist = false, .min = 1, .max = 0 },
	[REG_ID_VALUE_UID] = { .width_bytes = 1, .dtype = DTYPE_UINT, .perms = REG_R | REG_W, .offset = 433, .persist = false, .min = 1, .max = 0 },
	[REG_ID_VALUE_LOWEST_AVAILABLE_ID] = { .width_bytes = 1, .dtype = DTYPE_UINT, .perms = REG_R | REG_W, .offset = 434, .persist = false, .min = 1, .max = 0 },
	[REG_ID_VALUE_PERSISTS] = { .width_bytes = 1, .dtype = DTYPE_BOOL, .perms = REG_R | REG_W, .offset = 435, .persist = false, .min = 1, .max = 0 },
	[REG_ID_VALUE_AUTO_ID_MEATHOD] = { .width_bytes = 1, .dtype = DTYPE_ENUM, .perms = REG_R | REG_W, .offset = 436, .persist = false, .min = 1, .max = 0 },
	[REG_ID_AUTO_ID] = { .width_bytes = 0, .dtype = DTYPE_NONE, .perms = REG_CMD, .offset = 437, .persist = false, .min = 1, .max = 0 },
	[REG_ID_AUTO_ID_SELECT_NEXT] = { .width_bytes = 0, .dtype = DTYPE_NONE, .perms = REG_CMD, .offset = 437, .persist = false, .min = 1, .max = 0 },
	[REG_ID_AUTO_ID_SELECT_PREVIOUS] = { .width_bytes = 0, .dtype = DTYPE_NONE, .perms = REG_CMD, .offset = 437, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE] = { .width_bytes = 19, .dtype = DTYPE_NONE, .perms = 0, .offset = 437, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_CHANGE] = { .width_bytes = 0, .dtype = DTYPE_NONE, .perms = REG_CMD, .offset = 437, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_CHANGE_REBOOT] = { .width_bytes = 0, .dtype = DTYPE_NONE, .perms = REG_CMD, .offset = 437, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_CHANGE_ENTER_BOOT] = { .width_bytes = 0, .dtype = DTYPE_NONE, .perms = REG_CMD, .offset = 437, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_CHANGE_START] = { .width_bytes = 0, .dtype = DTYPE_NONE, .perms = REG_CMD, .offset = 437, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_CHANGE_STOP] = { .width_bytes = 0, .dtype = DTYPE_NONE, .perms = REG_CMD, .offset = 437, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_CHANGE_SLEEP] = { .width_bytes = 0, .dtype = DTYPE_NONE, .perms = REG_CMD, .offset = 437, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_CHANGE_DEEP_SLEEP] = { .width_bytes = 0, .dtype = DTYPE_NONE, .perms = REG_CMD, .offset = 437, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_CHANGE_WAKEUP] = { .width_bytes = 0, .dtype = DTYPE_NONE, .perms = REG_CMD, .offset = 437, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_CHANGE_NO_ID] = { .width_bytes = 0, .dtype = DTYPE_NONE, .perms = REG_CMD, .offset = 437, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_CURRENT] = { .width_bytes = 5, .dtype = DTYPE_NONE, .perms = REG_R, .offset = 437, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_CURRENT_STATE] = { .width_bytes = 1, .dtype = DTYPE_ENUM, .perms = REG_R, .offset = 437, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_CURRENT_REASON_IN_BOOT] = { .width_bytes = 1, .dtype = DTYPE_ENUM, .perms = REG_R, .offset = 438, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_CURRENT_REASON_STOPPED] = { .width_bytes = 1, .dtype = DTYPE_ENUM, .perms = REG_R, .offset = 439, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_CURRENT_REASON_SLEEPING] = { .width_bytes = 1, .dtype = DTYPE_ENUM, .perms = REG_R, .offset = 440, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_CURRENT_REASON_DEEP_SLEEPING] = { .width_bytes = 1, .dtype = DTYPE_ENUM, .perms = REG_R, .offset = 441, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_BEHAVIOR] = { .width_bytes = 10, .dtype = DTYPE_NONE, .perms = REG_R | REG_W, .offset = 442, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_BEHAVIOR_AUTO_JUMP] = { .width_bytes = 1, .dtype = DTYPE_BOOL, .perms = REG_R | REG_W, .offset = 442, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_BEHAVIOR_WAKE_ON_TIMER] = { .width_bytes = 1, .dtype = DTYPE_BOOL, .perms = REG_R | REG_W, .offset = 443, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_BEHAVIOR_SLEEP_WHEN_INACTIVE] = { .width_bytes = 1, .dtype = DTYPE_BOOL, .perms = REG_R | REG_W, .offset = 444, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_BEHAVIOR_DEEP_SLEEP_WHEN_INACTIVE] = { .width_bytes = 1, .dtype = DTYPE_BOOL, .perms = REG_R | REG_W, .offset = 445, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_BEHAVIOR_WAKE_TIMER_PERIOD] = { .width_bytes = 4, .dtype = DTYPE_UINT, .perms = REG_R | REG_W, .offset = 446, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_BEHAVIOR_INACTIVE_TIME] = { .width_bytes = 2, .dtype = DTYPE_UINT, .perms = REG_R | REG_W, .offset = 450, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_HEARTBEAT] = { .width_bytes = 4, .dtype = DTYPE_NONE, .perms = REG_R | REG_W, .offset = 452, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_HEARTBEAT_MY_BROADCAST] = { .width_bytes = 1, .dtype = DTYPE_BOOL, .perms = REG_R | REG_W, .offset = 452, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_HEARTBEAT_REQUIRE_RECIEVE] = { .width_bytes = 1, .dtype = DTYPE_UINT, .perms = REG_R | REG_W, .offset = 453, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_HEARTBEAT_TIME_TO_ACT] = { .width_bytes = 1, .dtype = DTYPE_UINT, .perms = REG_R | REG_W, .offset = 454, .persist = false, .min = 1, .max = 0 },
	[REG_NODE_STATE_HEARTBEAT_DEHAVIOR_ON_LOOSE] = { .width_bytes = 1, .dtype = DTYPE_ENUM, .perms = REG_R | REG_W, .offset = 455, .persist = false, .min = 1, .max = 0 },
};

typedef enum {
	CLEAR_FAULTS_ERROR_SUCCESS = 0,
	CLEAR_FAULTS_ERROR_FAILED = 1,
} faults_ctrl_clear_faults_error_t;

typedef enum {
	CLEAR_LOG_ERROR_SUCCESS = 0,
	CLEAR_LOG_ERROR_FAILED = 1,
} faults_ctrl_clear_log_error_t;

typedef enum {
	SELECT_NEXT_ERROR_SUCCESS = 0,
	SELECT_NEXT_ERROR_FAILED = 1,
} id_auto_id_select_next_error_t;

typedef enum {
	SELECT_PREVIOUS_ERROR_SUCCESS = 0,
	SELECT_PREVIOUS_ERROR_FAILED = 1,
} id_auto_id_select_previous_error_t;

typedef enum {
	REBOOT_ERROR_SUCCESS = 0,
	REBOOT_ERROR_FAILED = 1,
} node_state_change_reboot_error_t;

typedef enum {
	ENTER_BOOT_ERROR_SUCCESS = 0,
	ENTER_BOOT_ERROR_FAILED = 1,
} node_state_change_enter_boot_error_t;

typedef enum {
	START_ERROR_SUCCESS = 0,
	START_ERROR_FAILED = 1,
} node_state_change_start_error_t;

typedef enum {
	STOP_ERROR_SUCCESS = 0,
	STOP_ERROR_FAILED = 1,
} node_state_change_stop_error_t;

typedef enum {
	SLEEP_ERROR_SUCCESS = 0,
	SLEEP_ERROR_FAILED = 1,
} node_state_change_sleep_error_t;

typedef enum {
	DEEP_SLEEP_ERROR_SUCCESS = 0,
	DEEP_SLEEP_ERROR_FAILED = 1,
} node_state_change_deep_sleep_error_t;

typedef enum {
	WAKEUP_ERROR_SUCCESS = 0,
	WAKEUP_ERROR_FAILED = 1,
} node_state_change_wakeup_error_t;

typedef enum {
	NO_ID_ERROR_SUCCESS = 0,
	NO_ID_ERROR_FAILED = 1,
} node_state_change_no_id_error_t;


static inline int32_t faults_behavior_interval_to_ms(uint8_t raw) {
	return (int32_t)(raw * 100 + 0);
}

static inline uint8_t faults_behavior_interval_from_ms(int32_t eng) {
	return (uint8_t)((eng - 0) / 100);
}

static inline int32_t node_state_heartbeat_time_to_act_to_ms(uint8_t raw) {
	return (int32_t)(raw * 10 + 0);
}

static inline uint8_t node_state_heartbeat_time_to_act_from_ms(int32_t eng) {
	return (uint8_t)((eng - 0) / 10);
}


#endif