#ifndef DB_CAN_REG_MAP_H
#define DB_CAN_REG_MAP_H

/*
 * THIS FILE IS AUTOGENERATED CODE
 * DO NOT EDIT
*/

#include <stdint.h>
#include <stdbool.h>

/* @@CRC_DEFINE@@*/
/* @@REG_COUNT@@ */
/* @@REG_STORE_DECLARE@@ */


typedef enum {
    REG_R   = 1u << 0,
    REG_W   = 1u << 1,
    REG_CMD = 1u << 2
} reg_perm_t;

typedef enum {
    DTYPE_NONE = 0,
    /* @@DTYPE_ENUM@@ */
} dtype_t;

typedef enum {
    FIELD_DTYPE_NONE = 0,
    /* @@VALUE_DTYPE_ENUM*/
} field_dtype_t;

typedef enum {
    /* @@REGISTER_ENUM@@ */
} reg_map_t;

typedef struct {
    uint16_t    width_bytes;
    dtype_t     dtype;
    reg_perm_t  perms;
    uint16_t    offset;
} reg_desc_t;

/* @@REGISTER_ENUM_TYPES@@ */

/* @@REGISTER_STRUCT_TYPES@@ */

static const reg_desc_t reg_table[] = {
    /* @@REGISTER_TABLE@@ */
};

/* @@ERROR_ENUM_TYPES@@ */

#endif